### ISSUE TITLE
new version

### ISSUE THREAD

**Issue by ulamnet** [alashow/music-android#1]
where is the new wersion for android studio?

sorry my bad english.

**Comment by ulamnet** [comment]
Error:(59, 13) Failed to resolve: com.android.support:support-v4-preferencefragment:1.0.0
<a href="install.m2.repo">Install Repository and sync project</a><br><a href="openFile">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by alashow** [comment]
You don't need new version of android studio. You just need add preference-fragment to local maven repo. here http://stackoverflow.com/questions/22494120/add-project-as-library-in-android-studio

**Comment by ulamnet** [comment]
I'm not developer.

**Comment by ulamnet** [comment]
you have a skype ?
