### ISSUE TITLE
App Crashed

### ISSUE THREAD

**Issue by OoHerbethoO** [alashow/music-android#3]
Good night, now I'm having trouble with the Android application, what might be going wrong? Thank you in advance!

![captura de tela 2017-02-05 as 00 00 46](https://cloud.githubusercontent.com/assets/16544588/22623351/8e0ad5a0-eb36-11e6-996e-3d6dabc2585b.png)
![screenshot_1486263592](https://cloud.githubusercontent.com/assets/16544588/22623352/8e3cb8f4-eb36-11e6-8181-49fe992c334d.png)

**Comment by alashow** [comment]
I fixed this some time ago and squashed with the latest commit. But I forgot to force commit it.

Can you reclone it and try again?

But the actual error might be in your api. The fix is only fixes NPE.

**Comment by OoHerbethoO** [comment]
Now it is working perfectly. Thanks for the quick response and nimble. <3
